### PR TITLE
Make the :machine attribute required for machine_execute and machine_file lwrps.

### LINKED ISSUE #449: machine attribute in both machine_execute and machine_file resources should be required.
I declared a machine_execute block accidentally without specifying machine attribute. I made a bad assumption that the attribute was `:name_attribute`.

Anyway it failed when trying to connect to the machine but exception thrown was not in spot I expected.

 NoMethodError
    -------------
    undefined method `split' for nil:NilClass

https://github.com/chef/chef-provisioning/blob/63e88632122375476eb40a8a7a2db1e8b6d6b876/lib/chef/provisioning.rb#L46

Since my resources name attribute for resource is nil this [call](https://github.com/chef/chef-provisioning/blob/4638bdf99e048452b5b80e06c118ba2a0a0132a3/lib/chef/provisioning/chef_run_data.rb#L91) ended up setting machine_spec to object containing list of all machine managed entries. Since machine_spec in this case did not contain driver_url you hit the exception.

Suffice to say this confused me enough to have to walk-through the code. With the current implementation of machine_execute and machine_file resources I don't see how they can work without machine attribute declared. If we made the attribute required I believe it would result in error message which shows root cause of problem.

### PR DESCRIPTION
**Pull request by poliva83**
resolves #449

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tyler-ball** [comment]
Rebased and merged in 79e5279a42494983c829a8ab6df4c23bfc7a8b90. Thanks @poliva83 !

In chef-provisioning-aws we intentionally make most attributes not required so that you can reference a machine later in a recipe without having to continue specifying *all* the attributes you used to create it. But in the case of `machine_execute` and `machine_file` I think it makes sense to make them required.

We'll need to release this as at least a minor version bump since this is technically a breaking change.

**Comment by poliva83** [comment]
Thanks for merging @tyler-ball

**Pull request closed without merging**
