### PR TITLE
Fallback to BSD md5(1)

### LINKED ISSUE #289: machine[].create idempotency checks fails in freebsd
The call in [1] doesn't work because the md5sum doesn't exist in FreeBSD.

I ran this against the Bento FreeBSD 10.1 vmware_fusion image.

[1] https://github.com/chef/chef-provisioning/blob/c57ff2d3ea1b7c19f4676dde99ee613ccab190c4/lib/chef/provisioning/machine/unix_machine.rb#L46

### PR DESCRIPTION
**Pull request by aespinosa**
Fixes #289

### CODE REVIEW

**Comment by jkeiser** [comment]
@aespinosa I'm worried about cross-shell compatibility here.  I think we may be safer if we check the return code from the first run of md5sum in ruby, and try "md5" if it's nonzero.

**Comment by aespinosa** [comment]
Hi @jkeiser 

Ok, I'll make the shell check after reading the transport api a bit.

**Comment by aespinosa** [comment]
@jkeiser How does this look now?

According to my tests on FreeBSD, exitstatus is 1 for csh and 127 for sh

**Comment by aespinosa** [comment]
ping @jkeiser . let's hack on this tomorrow.

**Comment by jkeiser** [comment]
Grar, I didn't get back to this as soon as I'd have liked :(  This looks good now, merging!

**Comment by jkeiser** [comment]
Merged as 8b0e3a2

**Pull request closed without merging**
