### PR TITLE
Adding rubygems for on-premise mirror

### PR DESCRIPTION
**Pull request by juanxhos**
As same of PR https://github.com/chef/knife-windows/pull/418 

Signed-off-by: Juan Carlos Alonso Holmström <j.carlos.alonso.h@gmail.com>

### CODE REVIEW

**Review by mwrock — CHANGES_REQUESTED** [review]
The change looks good but please add `rubygems_url` to the convergence settings in the readme.

**Comment by jcalonsoh** [comment]
on behalf of https://discourse.chef.io/t/pre-release-announcement-chef-13-0/10723 Chef::Config[:rubygems_uri] from Chef::Config[:rubygems_url] on chef 13 usage

**Comment by mwrock** [comment]
I think you will want to clean up the PR. It should just include your rubygems commit.

**Comment by jcalonsoh** [comment]
Works well on chef 12, it was tested on https://travis-ci.org/chef/chef-provisioning/builds/219832457

**Review by mwrock — APPROVED** [review]

**Comment by mwrock** [comment]
I don't think the travis failure is related to this pr

**Comment by binpath** [comment]
Hey guys,
any update on this?

Thanks

**Pull request closed without merging**
