### PR TITLE
Add support for custom :install_sh_url

### LINKED ISSUE #474: Flexible install_command. Do not assume internet acces.
Currently chef-provisioning assume we have internet access to install chef. It would be super awesome if we could customize the `install_command` coming from here https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb#L44

### PR DESCRIPTION
**Pull request by SIGUSR2**
Fixes #474

### CODE REVIEW

**Comment by tyler-ball** [comment]
Thanks @SIGUSR2!

One note about this commit - I don't think the convergence options are persisted by default. Meaning, you will need to specify `install_sh_url` in the resource whenever the `converge` action will be performed.

In the future if this is messing people up, we could persist this setting in the `machine_spec`. But for now, this looks great!

**Comment by tyler-ball** [comment]
I was going to update the README when merging this, but I see this PR just brings reality in line with our documentation. Thanks!

**Comment by SIGUSR2** [comment]
Thank you!

**Comment by djapg** [comment]
Thank You!!

**Pull request merged**
