### PR TITLE
Marking lxc and hanlon as seeking maintainers

### PR DESCRIPTION
**Pull request by tyler-ball**
\cc @charlesjohnson @randomcamel 

We are deprecating support for chef-provisioning-(lxc|hanlon) and marking them as `maintainers wanted`.  Anyone interested in picking up maintainence should contact us on the chef-provisioning [gitter](https://gitter.im/chef/chef-provisioning).

### CODE REVIEW

**Comment by tyler-ball** [comment]
I added notes to the 2 READMEs

https://github.com/chef/chef-provisioning-lxc/blob/master/README.md
https://github.com/chef/chef-provisioning-hanlon/blob/master/README.md

**Comment by randomcamel** [comment]
:+1:

**Comment by charlesjohnson** [comment]
Can you please be more clear about the deprecation of these two drivers in the README.md notes in their respective repos?

Let's be clear that neither projects builds, or is actively maintained. We should probably also turn off issue reporting for both, and won't fix any open PRs / issues.

**Comment by charlesjohnson** [comment]
Update: I did my own needful. Good to go on my end. :)

**Comment by charlesjohnson** [comment]
Ah, we should turn off Travis for these projects as well.

**Comment by ranjib** [comment]
lxc wont work on travis unless they run the builds on kvm or something similar. i think they currently run on ovz or docker containers.
i'll get it tested with latest chef-provisioning

**Comment by hh** [comment]
I'm in motion (I live in an RV) so my physical test rig for hanlon isn't up.
I love working with it (for ii and on hanlon), but we move a lot and it often isn't powered up. Anyone up for hosting the hardware for me?

Where it is currently hosted:
https://twitter.com/hippiehacker/status/603979461537603584

What it can do:
https://youtu.be/5JvPI2zODuY?t=357

@csc @tjmcs ?

**Pull request merged**
